name: Create PDF report

on:
  push:
    branches:
     - master
     
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://dalibo/pandocker:latest
        with: 
          args: "README.md -o output/scrum-introduction.pdf --toc --pdf-engine=xelatex --template=./eisvogel.latex --listing -V mainfont=\"DejaVu Sans\""
      - uses: actions/upload-artifact@master
        with:
          name: scrum-introduction.pdf
          path: output
      - uses: docker://dalibo/pandocker:latest
        with: 
          args: "howto-start.md -o output/scrum-howto-start.pdf --toc --pdf-engine=xelatex --template=./eisvogel.latex --listing -V mainfont=\"DejaVu Sans\""
      - uses: actions/upload-artifact@master
        with:
          name: scrum-howto-start.pdf
          path: output
